language:
    nouncount: 6
    verbcount: 6
    blockcount: 100
    quantifiers: ["all", "some"]
    adjectives: ["red", "rose", ""]
    Neg: ["not", ""]
    RC: ["that sing", "that hum", ""]
traincells:
    intrablock: 10
    crossblock: 10
    coresets_percell: 1
testcells:
    intrablock: 2              #in-block cells, trained
    trained_crossblock: 2      #crossblock cells, trained
    fliptrained_crossblock: 5   #crossblock cells, untrained, w/ trained mirrors/'twins'
    untrained_crossblock: 10    #crossblock cells, untrained, flip untrained
    wug_count: 20        #crossblock cells XY where neither X nor Y has been crossed in train
    coresets_percell: 1
    neighbour_max_editdistance: 1